dist: xenial
services:
  - xvfb
language: node_js
node_js:
  '10'
addons:
  firefox: latest
sudo: false
install:
  - npm install -g yarn
  - yarn
script:
    set -e;
    pushd packages/widgets;
    yarn build;
    yarn minimize;
    popd;
    yarn clean;
    yarn build;
    yarn minimize;
    yarn build:test;
    yarn test;
    yarn docs;
    yarn api:check
