
name: lumino_documentation
channels:
  - conda-forge
  - nodefaults
dependencies:
- python=3.10
- jsx-lexer
- sphinx>=5.0
- sphinx-copybutton
- pydata_sphinx_theme
- myst_parser
- pytest
- pytest-check-links
- requests-cache
- pip
- nodejs
