#!/usr/bin/env python3
import sys
import shutil
import os

argv = sys.argv[1:] + ['--LabApp.collaborative', 'true']
print(argv)

with open('startup_args.txt', 'w') as fid:
    fid.write(str(argv))

os.execv(shutil.which(argv[0]), argv)
